### PR TITLE
WIP: feat: add shadow rule

### PR DESCRIPTION
**Pull request by Lvnszn**
**What this PR does**:
add shadow rule 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by jjeffcaii — APPROVED** [review]

**Review by Mulavar — APPROVED** [review]

**Comment by AlexStocks** [comment]
@Lvnszn If u think u have completed this pr, pls delete the WIP prefix.

**Comment by Lvnszn** [comment]
> @Lvnszn If u think u have completed this pr, pls delete the WIP prefix.

after weekly meeting and will improve this pr.

**Comment by dongzl** [comment]
```
shadow_rule:
    tables:
      - name: student
        enable: false
        cluster_group: employees_shadow
        match_rules:
          - operation: [insert,update]
            match_type: value
            attributes:
              column: uid
              value: 10000
          - operation: delete
            match_type: regex
            attributes:
              column: name
              regex: "^scott$"
          - operation: select
            match_type: hint
            attributes:
              shadow: true
```

**Comment by Lvnszn** [comment]
> ```
> shadow_rule:
>     tables:
>       - name: student
>         enable: false
>         cluster_group: employees_shadow
>         match_rules:
>           - operation: [insert,update]
>             match_type: value
>             attributes:
>               column: uid
>               value: 10000
>           - operation: delete
>             match_type: regex
>             attributes:
>               column: name
>               regex: "^scott$"
>           - operation: select
>             match_type: hint
>             attributes:
>               shadow: true
> ```

这里面有两个点要确认一下，1是 这个表要写到那个影子库里面，这块配置没指出来。第二点是 match_rules 太多的话，比如有10个表，就得写 >= 10个这种 operation. 符合预期不

**Comment by Lvnszn** [comment]
> ```
> shadow_rule:
>     tables:
>       - name: student
>         enable: false
>         cluster_group: employees_shadow
>         match_rules:
>           - operation: [insert,update]
>             match_type: value
>             attributes:
>               column: uid
>               value: 10000
>           - operation: delete
>             match_type: regex
>             attributes:
>               column: name
>               regex: "^scott$"
>           - operation: select
>             match_type: hint
>             attributes:
>               shadow: true
> ```

这里面有两个点要确认一下，1是 这个表要写到那个影子库里面，这块配置没指出来。第二点是 match_rules 太多的话，比如有10个表，就得写 >= 10个这种 operation. 符合预期不

**Comment by dongzl** [comment]
1、补充了一下文档内容，我想是在 `groups` 下面有个单独的 `node` -> `employees_shadow` ，就不需要单独创建一个 cluster 了。

2、现在配置的复用问题，算是共性问题，比如 `sharding_rule` 里面有个 `student_ course` 表，和 `student` 表 `sharding` 规则完全一样，也都是重复写一遍。

2 这个问题可以周会讨论，也需要解决。

**Review by AlexStocks — APPROVED** [review]

**Pull request closed without merging**
